#!/usr/bin/env perl

use strict;
use warnings;
use v5.10;
use utf8;
use IO::Handle;
STDOUT->autoflush(1);
STDERR->autoflush(1);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");

use sigtrap qw/die normal-signals/;

use JSON qw();

my $json = JSON->new->pretty->utf8;
my $i=0;
while(1) {
    $i++;
    say $json->encode({message => "Hello, world!",
		       iteration => $i});
    sleep 60;
}

